from prompts.trip_skeleton import generate_trip_skeleton_prompt
from prompts.itinerary import generate_travel_itinerary_prompt
from prompts.extra_days import generate_extra_days_prompt
from prompts.edit_itinerary import generate_edit_itinerary_prompt
